# CMake generated Testfile for 
# Source directory: /workspace/examples/25_ampere_fprop_mainloop_fusion
# Build directory: /workspace/custum/examples/25_ampere_fprop_mainloop_fusion
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_examples_25_ampere_fprop_mainloop_fusion]=] "/workspace/custum/examples/25_ampere_fprop_mainloop_fusion/25_ampere_fprop_mainloop_fusion")
set_tests_properties([=[ctest_examples_25_ampere_fprop_mainloop_fusion]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/25_ampere_fprop_mainloop_fusion/ctest/ctest_examples_25_ampere_fprop_mainloop_fusion/CTestTestfile.ctest_examples_25_ampere_fprop_mainloop_fusion.cmake;85;add_test;/workspace/custum/examples/25_ampere_fprop_mainloop_fusion/ctest/ctest_examples_25_ampere_fprop_mainloop_fusion/CTestTestfile.ctest_examples_25_ampere_fprop_mainloop_fusion.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/25_ampere_fprop_mainloop_fusion/CMakeLists.txt;32;cutlass_example_add_executable;/workspace/examples/25_ampere_fprop_mainloop_fusion/CMakeLists.txt;0;")
add_test([=[ctest_examples_25_ampere_3d_fprop_mainloop_fusion]=] "/workspace/custum/examples/25_ampere_fprop_mainloop_fusion/25_ampere_3d_fprop_mainloop_fusion")
set_tests_properties([=[ctest_examples_25_ampere_3d_fprop_mainloop_fusion]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/25_ampere_fprop_mainloop_fusion/ctest/ctest_examples_25_ampere_3d_fprop_mainloop_fusion/CTestTestfile.ctest_examples_25_ampere_3d_fprop_mainloop_fusion.cmake;85;add_test;/workspace/custum/examples/25_ampere_fprop_mainloop_fusion/ctest/ctest_examples_25_ampere_3d_fprop_mainloop_fusion/CTestTestfile.ctest_examples_25_ampere_3d_fprop_mainloop_fusion.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/25_ampere_fprop_mainloop_fusion/CMakeLists.txt;37;cutlass_example_add_executable;/workspace/examples/25_ampere_fprop_mainloop_fusion/CMakeLists.txt;0;")
