# CMake generated Testfile for 
# Source directory: /workspace/examples/cute/tutorial/hopper
# Build directory: /workspace/custum/examples/cute/tutorial/hopper
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_examples_cute_tutorial_wgmma_sm90]=] "/workspace/custum/examples/cute/tutorial/hopper/cute_tutorial_wgmma_sm90")
set_tests_properties([=[ctest_examples_cute_tutorial_wgmma_sm90]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/hopper/ctest/ctest_examples_cute_tutorial_wgmma_sm90/CTestTestfile.ctest_examples_cute_tutorial_wgmma_sm90.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/hopper/ctest/ctest_examples_cute_tutorial_wgmma_sm90/CTestTestfile.ctest_examples_cute_tutorial_wgmma_sm90.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/hopper/CMakeLists.txt;30;cutlass_example_add_executable;/workspace/examples/cute/tutorial/hopper/CMakeLists.txt;0;")
add_test([=[ctest_examples_cute_tutorial_wgmma_tma_sm90]=] "/workspace/custum/examples/cute/tutorial/hopper/cute_tutorial_wgmma_tma_sm90")
set_tests_properties([=[ctest_examples_cute_tutorial_wgmma_tma_sm90]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/hopper/ctest/ctest_examples_cute_tutorial_wgmma_tma_sm90/CTestTestfile.ctest_examples_cute_tutorial_wgmma_tma_sm90.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/hopper/ctest/ctest_examples_cute_tutorial_wgmma_tma_sm90/CTestTestfile.ctest_examples_cute_tutorial_wgmma_tma_sm90.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/hopper/CMakeLists.txt;35;cutlass_example_add_executable;/workspace/examples/cute/tutorial/hopper/CMakeLists.txt;0;")
