# CMake generated Testfile for 
# Source directory: /workspace/test/unit/cute/hopper
# Build directory: /workspace/custum/test/unit/cute/hopper
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_unit_cute_hopper_cooperative_gemm]=] "/workspace/custum/test/unit/cute/hopper/cutlass_test_unit_cute_hopper_cooperative_gemm" "--gtest_output=xml:test_unit_cute_hopper_cooperative_gemm.gtest.xml")
set_tests_properties([=[ctest_unit_cute_hopper_cooperative_gemm]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_cooperative_gemm/CTestTestfile.ctest_unit_cute_hopper_cooperative_gemm.cmake;85;add_test;/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_cooperative_gemm/CTestTestfile.ctest_unit_cute_hopper_cooperative_gemm.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/cute/hopper/CMakeLists.txt;50;cutlass_test_unit_add_executable;/workspace/test/unit/cute/hopper/CMakeLists.txt;0;")
add_test([=[ctest_unit_cute_hopper_stsm]=] "/workspace/custum/test/unit/cute/hopper/cutlass_test_unit_cute_hopper_stsm" "--gtest_output=xml:test_unit_cute_hopper_stsm.gtest.xml")
set_tests_properties([=[ctest_unit_cute_hopper_stsm]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_stsm/CTestTestfile.ctest_unit_cute_hopper_stsm.cmake;85;add_test;/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_stsm/CTestTestfile.ctest_unit_cute_hopper_stsm.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/cute/hopper/CMakeLists.txt;55;cutlass_test_unit_add_executable;/workspace/test/unit/cute/hopper/CMakeLists.txt;0;")
add_test([=[ctest_unit_cute_hopper_tma_load]=] "/workspace/custum/test/unit/cute/hopper/cutlass_test_unit_cute_hopper_tma_load" "--gtest_output=xml:test_unit_cute_hopper_tma_load.gtest.xml")
set_tests_properties([=[ctest_unit_cute_hopper_tma_load]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_tma_load/CTestTestfile.ctest_unit_cute_hopper_tma_load.cmake;85;add_test;/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_tma_load/CTestTestfile.ctest_unit_cute_hopper_tma_load.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/cute/hopper/CMakeLists.txt;60;cutlass_test_unit_add_executable;/workspace/test/unit/cute/hopper/CMakeLists.txt;0;")
add_test([=[ctest_unit_cute_hopper_tma_mcast_load]=] "/workspace/custum/test/unit/cute/hopper/cutlass_test_unit_cute_hopper_tma_mcast_load" "--gtest_output=xml:test_unit_cute_hopper_tma_mcast_load.gtest.xml")
set_tests_properties([=[ctest_unit_cute_hopper_tma_mcast_load]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_tma_mcast_load/CTestTestfile.ctest_unit_cute_hopper_tma_mcast_load.cmake;85;add_test;/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_tma_mcast_load/CTestTestfile.ctest_unit_cute_hopper_tma_mcast_load.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/cute/hopper/CMakeLists.txt;65;cutlass_test_unit_add_executable;/workspace/test/unit/cute/hopper/CMakeLists.txt;0;")
add_test([=[ctest_unit_cute_hopper_tma_store]=] "/workspace/custum/test/unit/cute/hopper/cutlass_test_unit_cute_hopper_tma_store" "--gtest_output=xml:test_unit_cute_hopper_tma_store.gtest.xml")
set_tests_properties([=[ctest_unit_cute_hopper_tma_store]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_tma_store/CTestTestfile.ctest_unit_cute_hopper_tma_store.cmake;85;add_test;/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_tma_store/CTestTestfile.ctest_unit_cute_hopper_tma_store.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/cute/hopper/CMakeLists.txt;70;cutlass_test_unit_add_executable;/workspace/test/unit/cute/hopper/CMakeLists.txt;0;")
add_test([=[ctest_unit_cute_hopper_bulk_load]=] "/workspace/custum/test/unit/cute/hopper/cutlass_test_unit_cute_hopper_bulk_load" "--gtest_output=xml:test_unit_cute_hopper_bulk_load.gtest.xml")
set_tests_properties([=[ctest_unit_cute_hopper_bulk_load]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_bulk_load/CTestTestfile.ctest_unit_cute_hopper_bulk_load.cmake;85;add_test;/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_bulk_load/CTestTestfile.ctest_unit_cute_hopper_bulk_load.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/cute/hopper/CMakeLists.txt;75;cutlass_test_unit_add_executable;/workspace/test/unit/cute/hopper/CMakeLists.txt;0;")
add_test([=[ctest_unit_cute_hopper_bulk_store]=] "/workspace/custum/test/unit/cute/hopper/cutlass_test_unit_cute_hopper_bulk_store" "--gtest_output=xml:test_unit_cute_hopper_bulk_store.gtest.xml")
set_tests_properties([=[ctest_unit_cute_hopper_bulk_store]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_bulk_store/CTestTestfile.ctest_unit_cute_hopper_bulk_store.cmake;85;add_test;/workspace/custum/test/unit/cute/hopper/ctest/ctest_unit_cute_hopper_bulk_store/CTestTestfile.ctest_unit_cute_hopper_bulk_store.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/cute/hopper/CMakeLists.txt;80;cutlass_test_unit_add_executable;/workspace/test/unit/cute/hopper/CMakeLists.txt;0;")
