# CMake generated Testfile for 
# Source directory: /workspace/test/unit/conv/device
# Build directory: /workspace/custum/test/unit/conv/device
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_unit_conv_device_simt]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_simt" "--gtest_output=xml:test_unit_conv_device_simt.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_simt]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_simt/CTestTestfile.ctest_unit_conv_device_simt.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_simt/CTestTestfile.ctest_unit_conv_device_simt.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;114;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_f32_sm70]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_f32_sm70" "--gtest_output=xml:test_unit_conv_device_tensorop_f32_sm70.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_f32_sm70]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_sm70/CTestTestfile.ctest_unit_conv_device_tensorop_f32_sm70.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_sm70/CTestTestfile.ctest_unit_conv_device_tensorop_f32_sm70.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;165;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_f32_sm75]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_f32_sm75" "--gtest_output=xml:test_unit_conv_device_tensorop_f32_sm75.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_f32_sm75]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_sm75/CTestTestfile.ctest_unit_conv_device_tensorop_f32_sm75.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_sm75/CTestTestfile.ctest_unit_conv_device_tensorop_f32_sm75.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;174;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_f16_sm80]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_f16_sm80" "--gtest_output=xml:test_unit_conv_device_tensorop_f16_sm80.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_f16_sm80]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f16_sm80/CTestTestfile.ctest_unit_conv_device_tensorop_f16_sm80.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f16_sm80/CTestTestfile.ctest_unit_conv_device_tensorop_f16_sm80.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;191;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_f32_sm80]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_f32_sm80" "--gtest_output=xml:test_unit_conv_device_tensorop_f32_sm80.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_f32_sm80]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_sm80/CTestTestfile.ctest_unit_conv_device_tensorop_f32_sm80.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_sm80/CTestTestfile.ctest_unit_conv_device_tensorop_f32_sm80.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;200;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_f32_tf32_sm80]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_f32_tf32_sm80" "--gtest_output=xml:test_unit_conv_device_tensorop_f32_tf32_sm80.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_f32_tf32_sm80]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_tf32_sm80/CTestTestfile.ctest_unit_conv_device_tensorop_f32_tf32_sm80.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f32_tf32_sm80/CTestTestfile.ctest_unit_conv_device_tensorop_f32_tf32_sm80.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;226;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_s32]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_s32" "--gtest_output=xml:test_unit_conv_device_tensorop_s32.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_s32]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_s32/CTestTestfile.ctest_unit_conv_device_tensorop_s32.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_s32/CTestTestfile.ctest_unit_conv_device_tensorop_s32.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;243;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_s32_interleaved]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_s32_interleaved" "--gtest_output=xml:test_unit_conv_device_tensorop_s32_interleaved.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_s32_interleaved]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_s32_interleaved/CTestTestfile.ctest_unit_conv_device_tensorop_s32_interleaved.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_s32_interleaved/CTestTestfile.ctest_unit_conv_device_tensorop_s32_interleaved.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;250;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv_device_tensorop_f8_sm89]=] "/workspace/custum/test/unit/conv/device/cutlass_test_unit_conv_device_tensorop_f8_sm89" "--gtest_output=xml:test_unit_conv_device_tensorop_f8_sm89.gtest.xml")
set_tests_properties([=[ctest_unit_conv_device_tensorop_f8_sm89]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f8_sm89/CTestTestfile.ctest_unit_conv_device_tensorop_f8_sm89.cmake;85;add_test;/workspace/custum/test/unit/conv/device/ctest/ctest_unit_conv_device_tensorop_f8_sm89/CTestTestfile.ctest_unit_conv_device_tensorop_f8_sm89.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device/CMakeLists.txt;280;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device/CMakeLists.txt;0;")
