# CMake generated Testfile for 
# Source directory: /workspace/test/unit/transform/device
# Build directory: /workspace/custum/test/unit/transform/device
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_unit_sm90_structured_sparse_gemm_compressor_f32]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm90_structured_sparse_gemm_compressor_f32" "--gtest_output=xml:test_unit_sm90_structured_sparse_gemm_compressor_f32.gtest.xml")
set_tests_properties([=[ctest_unit_sm90_structured_sparse_gemm_compressor_f32]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm90_structured_sparse_gemm_compressor_f32/CTestTestfile.ctest_unit_sm90_structured_sparse_gemm_compressor_f32.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm90_structured_sparse_gemm_compressor_f32/CTestTestfile.ctest_unit_sm90_structured_sparse_gemm_compressor_f32.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;41;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm90_structured_sparse_gemm_compressor_f16]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm90_structured_sparse_gemm_compressor_f16" "--gtest_output=xml:test_unit_sm90_structured_sparse_gemm_compressor_f16.gtest.xml")
set_tests_properties([=[ctest_unit_sm90_structured_sparse_gemm_compressor_f16]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm90_structured_sparse_gemm_compressor_f16/CTestTestfile.ctest_unit_sm90_structured_sparse_gemm_compressor_f16.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm90_structured_sparse_gemm_compressor_f16/CTestTestfile.ctest_unit_sm90_structured_sparse_gemm_compressor_f16.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;47;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm90_structured_sparse_gemm_compressor_f8]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm90_structured_sparse_gemm_compressor_f8" "--gtest_output=xml:test_unit_sm90_structured_sparse_gemm_compressor_f8.gtest.xml")
set_tests_properties([=[ctest_unit_sm90_structured_sparse_gemm_compressor_f8]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm90_structured_sparse_gemm_compressor_f8/CTestTestfile.ctest_unit_sm90_structured_sparse_gemm_compressor_f8.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm90_structured_sparse_gemm_compressor_f8/CTestTestfile.ctest_unit_sm90_structured_sparse_gemm_compressor_f8.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;53;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f32]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm100_structured_sparse_gemm_compressor_f32" "--gtest_output=xml:test_unit_sm100_structured_sparse_gemm_compressor_f32.gtest.xml")
set_tests_properties([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f32]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f32/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f32.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f32/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f32.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;70;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f16]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm100_structured_sparse_gemm_compressor_f16" "--gtest_output=xml:test_unit_sm100_structured_sparse_gemm_compressor_f16.gtest.xml")
set_tests_properties([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f16]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f16/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f16.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f16/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f16.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;76;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f8]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm100_structured_sparse_gemm_compressor_f8" "--gtest_output=xml:test_unit_sm100_structured_sparse_gemm_compressor_f8.gtest.xml")
set_tests_properties([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f8]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f8/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f8.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f8/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f8.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;82;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f6]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm100_structured_sparse_gemm_compressor_f6" "--gtest_output=xml:test_unit_sm100_structured_sparse_gemm_compressor_f6.gtest.xml")
set_tests_properties([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f6]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f6/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f6.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f6/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f6.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;88;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f4_qmma]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm100_structured_sparse_gemm_compressor_f4_qmma" "--gtest_output=xml:test_unit_sm100_structured_sparse_gemm_compressor_f4_qmma.gtest.xml")
set_tests_properties([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f4_qmma]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f4_qmma/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f4_qmma.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f4_qmma/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f4_qmma.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;94;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
add_test([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f4_omma]=] "/workspace/custum/test/unit/transform/device/cutlass_test_unit_sm100_structured_sparse_gemm_compressor_f4_omma" "--gtest_output=xml:test_unit_sm100_structured_sparse_gemm_compressor_f4_omma.gtest.xml")
set_tests_properties([=[ctest_unit_sm100_structured_sparse_gemm_compressor_f4_omma]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f4_omma/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f4_omma.cmake;85;add_test;/workspace/custum/test/unit/transform/device/ctest/ctest_unit_sm100_structured_sparse_gemm_compressor_f4_omma/CTestTestfile.ctest_unit_sm100_structured_sparse_gemm_compressor_f4_omma.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/transform/device/CMakeLists.txt;100;cutlass_test_unit_add_executable;/workspace/test/unit/transform/device/CMakeLists.txt;0;")
