# CMake generated Testfile for 
# Source directory: /workspace/examples/86_blackwell_mixed_dtype_gemm
# Build directory: /workspace/custum/examples/86_blackwell_mixed_dtype_gemm
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_tile_shape]=] "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/86_blackwell_mixed_dtype_gemm" "--m=256" "--n=128" "--k=32" "--verify" "--iterations=0")
set_tests_properties([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_tile_shape]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;85;add_test;/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;36;cutlass_example_add_executable;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;0;")
add_test([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_tile_shape_multiple_kiter]=] "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/86_blackwell_mixed_dtype_gemm" "--m=256" "--n=128" "--k=128" "--verify" "--iterations=0")
set_tests_properties([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_tile_shape_multiple_kiter]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;128;add_test;/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;36;cutlass_example_add_executable;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;0;")
add_test([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_one_wave]=] "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/86_blackwell_mixed_dtype_gemm" "--m=1536" "--n=1536" "--k=32" "--verify" "--iterations=0")
set_tests_properties([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_one_wave]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;171;add_test;/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;36;cutlass_example_add_executable;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;0;")
add_test([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_2048]=] "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/86_blackwell_mixed_dtype_gemm" "--m=2048" "--n=2048" "--k=2048" "--verify" "--iterations=0")
set_tests_properties([=[ctest_examples_86_blackwell_mixed_dtype_gemm_test_s_2048]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;214;add_test;/workspace/custum/examples/86_blackwell_mixed_dtype_gemm/ctest/ctest_examples_86_blackwell_mixed_dtype_gemm/CTestTestfile.ctest_examples_86_blackwell_mixed_dtype_gemm.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;36;cutlass_example_add_executable;/workspace/examples/86_blackwell_mixed_dtype_gemm/CMakeLists.txt;0;")
