# CMake generated Testfile for 
# Source directory: /workspace/tools/profiler
# Build directory: /workspace/custum/tools/profiler
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_profiler_gemm]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=BlockScaledGemm" "--providers=cutlass" "--verification-providers=cublas,device" "--junit-output=test_cutlass_profiler_gemm" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_gemm]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;85;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_conv2d]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=Conv2d" "--providers=cutlass" "--verification-providers=cudnn,device" "--junit-output=test_cutlass_profiler_conv2d" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_conv2d]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;128;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_conv3d]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=Conv3d" "--providers=cutlass" "--verification-providers=cudnn,device,host" "--junit-output=test_cutlass_profiler_conv3d" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_conv3d]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;171;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_spgemm]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=SparseGemm" "--providers=cutlass" "--verification-providers=cublas,device,host" "--junit-output=test_cutlass_profiler_spgemm" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_spgemm]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;214;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_rank_k]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=RankK" "--providers=cutlass" "--verification-providers=cublas" "--junit-output=test_cutlass_profiler_rank_k" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_rank_k]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;257;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_rank_2k]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=Rank2K" "--providers=cutlass" "--verification-providers=cublas" "--junit-output=test_cutlass_profiler_rank_2k" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_rank_2k]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;300;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_trmm]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=Trmm" "--providers=cutlass" "--verification-providers=device,host" "--junit-output=test_cutlass_profiler_trmm" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_trmm]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;343;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_symm]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=Symm" "--providers=cutlass" "--verification-providers=cublas,host" "--junit-output=test_cutlass_profiler_symm" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_symm]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;386;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
add_test([=[ctest_profiler_grouped_gemm]=] "/workspace/custum/tools/profiler/cutlass_profiler" "--operation=GroupedGemm" "--providers=cutlass" "--verification-providers=device" "--junit-output=test_cutlass_profiler_grouped_gemm" "--print-kernel-before-running=true")
set_tests_properties([=[ctest_profiler_grouped_gemm]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;429;add_test;/workspace/custum/tools/profiler/ctest/ctest_profiler/CTestTestfile.ctest_profiler.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/tools/profiler/CMakeLists.txt;119;cutlass_add_executable_tests;/workspace/tools/profiler/CMakeLists.txt;0;")
