# CMake generated Testfile for 
# Source directory: /workspace/examples/41_fused_multi_head_attention
# Build directory: /workspace/custum/examples/41_fused_multi_head_attention
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_examples_41_fused_multi_head_attention_fixed_seqlen]=] "/workspace/custum/examples/41_fused_multi_head_attention/41_fused_multi_head_attention_fixed_seqlen")
set_tests_properties([=[ctest_examples_41_fused_multi_head_attention_fixed_seqlen]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/41_fused_multi_head_attention/ctest/ctest_examples_41_fused_multi_head_attention_fixed_seqlen/CTestTestfile.ctest_examples_41_fused_multi_head_attention_fixed_seqlen.cmake;85;add_test;/workspace/custum/examples/41_fused_multi_head_attention/ctest/ctest_examples_41_fused_multi_head_attention_fixed_seqlen/CTestTestfile.ctest_examples_41_fused_multi_head_attention_fixed_seqlen.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;30;cutlass_example_add_executable;/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;0;")
add_test([=[ctest_examples_41_fused_multi_head_attention_variable_seqlen]=] "/workspace/custum/examples/41_fused_multi_head_attention/41_fused_multi_head_attention_variable_seqlen")
set_tests_properties([=[ctest_examples_41_fused_multi_head_attention_variable_seqlen]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/41_fused_multi_head_attention/ctest/ctest_examples_41_fused_multi_head_attention_variable_seqlen/CTestTestfile.ctest_examples_41_fused_multi_head_attention_variable_seqlen.cmake;85;add_test;/workspace/custum/examples/41_fused_multi_head_attention/ctest/ctest_examples_41_fused_multi_head_attention_variable_seqlen/CTestTestfile.ctest_examples_41_fused_multi_head_attention_variable_seqlen.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;35;cutlass_example_add_executable;/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;0;")
add_test([=[ctest_examples_41_fused_multi_head_attention_backward]=] "/workspace/custum/examples/41_fused_multi_head_attention/41_fused_multi_head_attention_backward")
set_tests_properties([=[ctest_examples_41_fused_multi_head_attention_backward]=] PROPERTIES  DISABLED "ON" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/41_fused_multi_head_attention/ctest/ctest_examples_41_fused_multi_head_attention_backward/CTestTestfile.ctest_examples_41_fused_multi_head_attention_backward.cmake;85;add_test;/workspace/custum/examples/41_fused_multi_head_attention/ctest/ctest_examples_41_fused_multi_head_attention_backward/CTestTestfile.ctest_examples_41_fused_multi_head_attention_backward.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;40;cutlass_example_add_executable;/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;0;")
add_test([=[ctest_examples_41_fmha_backward_python]=] "/usr/bin/python3.12" "/workspace/examples/41_fused_multi_head_attention/fmha_backward_test.py" "/workspace/custum/examples/41_fused_multi_head_attention/41_fused_multi_head_attention_backward")
set_tests_properties([=[ctest_examples_41_fmha_backward_python]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;53;add_test;/workspace/examples/41_fused_multi_head_attention/CMakeLists.txt;0;")
