# CMake generated Testfile for 
# Source directory: /workspace/examples/cute/tutorial
# Build directory: /workspace/custum/examples/cute/tutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_examples_cute_tutorial_sgemm_1]=] "/workspace/custum/examples/cute/tutorial/cute_tutorial_sgemm_1")
set_tests_properties([=[ctest_examples_cute_tutorial_sgemm_1]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_1/CTestTestfile.ctest_examples_cute_tutorial_sgemm_1.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_1/CTestTestfile.ctest_examples_cute_tutorial_sgemm_1.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/CMakeLists.txt;33;cutlass_example_add_executable;/workspace/examples/cute/tutorial/CMakeLists.txt;0;")
add_test([=[ctest_examples_cute_tutorial_sgemm_2]=] "/workspace/custum/examples/cute/tutorial/cute_tutorial_sgemm_2")
set_tests_properties([=[ctest_examples_cute_tutorial_sgemm_2]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_2/CTestTestfile.ctest_examples_cute_tutorial_sgemm_2.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_2/CTestTestfile.ctest_examples_cute_tutorial_sgemm_2.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/CMakeLists.txt;38;cutlass_example_add_executable;/workspace/examples/cute/tutorial/CMakeLists.txt;0;")
add_test([=[ctest_examples_cute_tutorial_sgemm_sm70]=] "/workspace/custum/examples/cute/tutorial/cute_tutorial_sgemm_sm70")
set_tests_properties([=[ctest_examples_cute_tutorial_sgemm_sm70]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_sm70/CTestTestfile.ctest_examples_cute_tutorial_sgemm_sm70.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_sm70/CTestTestfile.ctest_examples_cute_tutorial_sgemm_sm70.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/CMakeLists.txt;43;cutlass_example_add_executable;/workspace/examples/cute/tutorial/CMakeLists.txt;0;")
add_test([=[ctest_examples_cute_tutorial_sgemm_sm80]=] "/workspace/custum/examples/cute/tutorial/cute_tutorial_sgemm_sm80")
set_tests_properties([=[ctest_examples_cute_tutorial_sgemm_sm80]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_sm80/CTestTestfile.ctest_examples_cute_tutorial_sgemm_sm80.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_sgemm_sm80/CTestTestfile.ctest_examples_cute_tutorial_sgemm_sm80.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/CMakeLists.txt;48;cutlass_example_add_executable;/workspace/examples/cute/tutorial/CMakeLists.txt;0;")
add_test([=[ctest_examples_cute_tutorial_tiled_copy]=] "/workspace/custum/examples/cute/tutorial/cute_tutorial_tiled_copy")
set_tests_properties([=[ctest_examples_cute_tutorial_tiled_copy]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_tiled_copy/CTestTestfile.ctest_examples_cute_tutorial_tiled_copy.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_tiled_copy/CTestTestfile.ctest_examples_cute_tutorial_tiled_copy.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/CMakeLists.txt;53;cutlass_example_add_executable;/workspace/examples/cute/tutorial/CMakeLists.txt;0;")
add_test([=[ctest_examples_cute_tutorial_tiled_copy_if]=] "/workspace/custum/examples/cute/tutorial/cute_tutorial_tiled_copy_if")
set_tests_properties([=[ctest_examples_cute_tutorial_tiled_copy_if]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_tiled_copy_if/CTestTestfile.ctest_examples_cute_tutorial_tiled_copy_if.cmake;85;add_test;/workspace/custum/examples/cute/tutorial/ctest/ctest_examples_cute_tutorial_tiled_copy_if/CTestTestfile.ctest_examples_cute_tutorial_tiled_copy_if.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/examples/CMakeLists.txt;71;cutlass_add_executable_tests;/workspace/examples/cute/tutorial/CMakeLists.txt;58;cutlass_example_add_executable;/workspace/examples/cute/tutorial/CMakeLists.txt;0;")
subdirs("hopper")
subdirs("blackwell")
