# CMake generated Testfile for 
# Source directory: /workspace/test/unit/conv/device_3x/fprop
# Build directory: /workspace/custum/test/unit/conv/device_3x/fprop
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest_unit_conv1d_fprop_device_tensorop_sm90]=] "/workspace/custum/test/unit/conv/device_3x/fprop/cutlass_test_unit_conv1d_fprop_device_tensorop_sm90" "--gtest_output=xml:test_unit_conv1d_fprop_device_tensorop_sm90.gtest.xml")
set_tests_properties([=[ctest_unit_conv1d_fprop_device_tensorop_sm90]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device_3x/fprop/ctest/ctest_unit_conv1d_fprop_device_tensorop_sm90/CTestTestfile.ctest_unit_conv1d_fprop_device_tensorop_sm90.cmake;85;add_test;/workspace/custum/test/unit/conv/device_3x/fprop/ctest/ctest_unit_conv1d_fprop_device_tensorop_sm90/CTestTestfile.ctest_unit_conv1d_fprop_device_tensorop_sm90.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device_3x/fprop/CMakeLists.txt;40;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device_3x/fprop/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv2d_fprop_device_tensorop_sm90]=] "/workspace/custum/test/unit/conv/device_3x/fprop/cutlass_test_unit_conv2d_fprop_device_tensorop_sm90" "--gtest_output=xml:test_unit_conv2d_fprop_device_tensorop_sm90.gtest.xml")
set_tests_properties([=[ctest_unit_conv2d_fprop_device_tensorop_sm90]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device_3x/fprop/ctest/ctest_unit_conv2d_fprop_device_tensorop_sm90/CTestTestfile.ctest_unit_conv2d_fprop_device_tensorop_sm90.cmake;85;add_test;/workspace/custum/test/unit/conv/device_3x/fprop/ctest/ctest_unit_conv2d_fprop_device_tensorop_sm90/CTestTestfile.ctest_unit_conv2d_fprop_device_tensorop_sm90.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device_3x/fprop/CMakeLists.txt;53;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device_3x/fprop/CMakeLists.txt;0;")
add_test([=[ctest_unit_conv3d_fprop_device_tensorop_sm90]=] "/workspace/custum/test/unit/conv/device_3x/fprop/cutlass_test_unit_conv3d_fprop_device_tensorop_sm90" "--gtest_output=xml:test_unit_conv3d_fprop_device_tensorop_sm90.gtest.xml")
set_tests_properties([=[ctest_unit_conv3d_fprop_device_tensorop_sm90]=] PROPERTIES  DISABLED "OFF" WORKING_DIRECTORY "./bin" _BACKTRACE_TRIPLES "/workspace/custum/test/unit/conv/device_3x/fprop/ctest/ctest_unit_conv3d_fprop_device_tensorop_sm90/CTestTestfile.ctest_unit_conv3d_fprop_device_tensorop_sm90.cmake;85;add_test;/workspace/custum/test/unit/conv/device_3x/fprop/ctest/ctest_unit_conv3d_fprop_device_tensorop_sm90/CTestTestfile.ctest_unit_conv3d_fprop_device_tensorop_sm90.cmake;0;;/workspace/CMakeLists.txt;1043;include;/workspace/test/unit/CMakeLists.txt;118;cutlass_add_executable_tests;/workspace/test/unit/conv/device_3x/fprop/CMakeLists.txt;66;cutlass_test_unit_add_executable;/workspace/test/unit/conv/device_3x/fprop/CMakeLists.txt;0;")
